Add F5 key to toggle fullscreen
hndada/gosu pull request #15
Opened 2022-10-22 07:22 UTC by Supernovaysi

F5 키를 누르면 전체화면이 되도록 만들었습니다.

2022-10-23 00:52 UTC, hndada commented
개선되었으면 하는 코드에 코멘트를 남겼습니다.

2022-10-23 09:15 UTC, Supernovaysi commented
코멘트가 보이지 않습니다

2022-10-24 04:59 UTC, hndada requested changes

2022-10-24 04:59 UTC, hndada commented on game.go
> +	ebiten.SetFullscreen(isFullScreen)
review를 Pending으로 남겨둔 채로 두어서 보이지 않았습니다.

2026-09-20 13:00 UTC, closed without merging